### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Shiv-Patil** [prateekmedia/Menu11#16]
Whenever I click on it, it shows
`Error loading QML file: file:///home/krymzin/.local/share/plasma/plasmoids/menu11/contents/ui/main.qml:60:9: Type MenuRepresentation unavailable
file:///home/krymzin/.local/share/plasma/plasmoids/menu11/contents/ui/MenuRepresentation.qml:136:13: Type MainColumnItem unavailable
file:///home/krymzin/.local/share/plasma/plasmoids/menu11/contents/ui/MainColumnItem.qml:302:9: Type ItemGridView unavailable
file:///home/krymzin/.local/share/plasma/plasmoids/menu11/contents/ui/ItemGridView.qml:191:13: Type ItemGridDelegate2 unavailable
file:///home/krymzin/.local/share/plasma/plasmoids/menu11/contents/ui/ItemGridDelegate2.qml:20:1: module "QtQuick" version 2.14 is not installed`

Plasma version: 5.18.5
Qt version: 5.12.8

I have installed kde plasma on linux mint

**Comment by ASOwnerYT** [comment]
I'm getting a very similar error, on Garuda (Arch-based) Linux.

```
file:///home/asowneryt/.local/share/plasma/plasmoids/menu11/contents/ui/main.qml:60:9: Type MenuRepresentation unavailable

file:///home/asowneryt/.local/share/plasma/plasmoids/menu11/contents/ui/MenuRepresentation.qml:136:13: Type MainColumnItem unavailable

file:///home/asowneryt/.local/share/plasma/plasmoids/menu11/contents/ui/MainColumnItem.qml:531:5: Type Footer unavailable

file:///home/asowneryt/.local/share/plasma/plasmoids/menu11/contents/ui/Footer.qml:30:1: module "org.kde.plasma.private.quicklaunch" is not installed
```

**Comment by ASOwnerYT** [comment]
[Found a solution](https://github.com/prateekmedia/Menu11/issues/10#issuecomment-873423156), but I'm using an arch-based Linux distro, so how do I install `plasma-widgets-addons` on Arch Linux?

**Comment by Shiv-Patil** [comment]
@ASOwnerYT This is not related to my issue, it is different. Take a look in closed issues, iirc I found 2 issues relating to yours.

**Comment by ASOwnerYT** [comment]
> @ASOwnerYT This is not related to my issue, it is different. Take a look in closed issues, iirc I found 2 issues relating to yours.

Oh sorry lol, the error messages look quite similar, but after I posted that comment I found the 2 issues with my exact error message. Sorry!

**Comment by prateekmedia** [comment]
@Shiv-Patil 
Your plasma version is old, hence this is not working.

What you can do is manually change the QtQuick version from the file to 2.12 or 2.10 whatever works for you.

I will try to change it also in the code if it doesn't break if.

**Comment by Shiv-Patil** [comment]
I guess it does break things, because I get a new error

`Error loading QML file: file:///home/krymzin/.local/share/plasma/plasmoids/menu11/contents/ui/main.qml:60:9: Type MenuRepresentation unavailable
file:///home/krymzin/.local/share/plasma/plasmoids/menu11/contents/ui/MenuRepresentation.qml:136:13: Type MainColumnItem unavailable
file:///home/krymzin/.local/share/plasma/plasmoids/menu11/contents/ui/MainColumnItem.qml:530:5: Type Footer unavailable
file:///home/krymzin/.local/share/plasma/plasmoids/menu11/contents/ui/Footer.qml:32:1: PlasmaExtras.PlasmoidHeading is not a type`

Maybe I'll have to wait until a newer plasma version comes around.

**Comment by prateekmedia** [comment]
Reinstall it with readme command, it should work now.

**Comment by Shiv-Patil** [comment]
> Reinstall it with readme command, it should work now.

`Error loading QML file: file:///home/krymzin/.local/share/plasma/plasmoids/menu11/contents/ui/main.qml:60:9: Type MenuRepresentation unavailable
file:///home/krymzin/.local/share/plasma/plasmoids/menu11/contents/ui/MenuRepresentation.qml:136:13: Type MainColumnItem unavailable
file:///home/krymzin/.local/share/plasma/plasmoids/menu11/contents/ui/MainColumnItem.qml:533:5: Type Footer unavailable
file:///home/krymzin/.local/share/plasma/plasmoids/menu11/contents/ui/Footer.qml:32:1: PlasmaExtras.PlasmoidHeading is not a type
`

**Comment by prateekmedia** [comment]
@Shiv-Patil Please remove the menu11 folder path from plasmoids and use the below command to reinstall it, if problem persists then I will help you.

```
git clone https://github.com/prateekmedia/Menu11.git ~/.local/share/plasma/plasmoids/menu11;
kquitapp5 plasmashell || killall plasmashell && kstart5 plasmashell;
```

**Comment by Shiv-Patil** [comment]
That's exactly what I did, I even did a system reboot after deleting, then cloned; still doesn't work.

**Comment by Shiv-Patil** [comment]
> `Error loading QML file: file:///home/krymzin/.local/share/plasma/plasmoids/menu11/contents/ui/main.qml:60:9: Type MenuRepresentation unavailable file:///home/krymzin/.local/share/plasma/plasmoids/menu11/contents/ui/MenuRepresentation.qml:136:13: Type MainColumnItem unavailable file:///home/krymzin/.local/share/plasma/plasmoids/menu11/contents/ui/MainColumnItem.qml:533:5: Type Footer unavailable file:///home/krymzin/.local/share/plasma/plasmoids/menu11/contents/ui/Footer.qml:32:1: PlasmaExtras.PlasmoidHeading is not a type `

I'm getting this error.

**Comment by prateekmedia** [comment]
Hi @Shiv-Patil 

I will try replacing that with something more backward compatible, till then please hold.

**Comment by prateekmedia** [comment]
Fixed in the latest version,
